# todo: releasing https://github.com/lannonbr/vsce-action
name: Main

on: push

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [11, 12]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Test
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm install
        npm run build --if-present
        npm test